import { TravelRequest, TripType, TravelMode, Priority, ApprovalStatus, PNCStatus } from '../types';

/**
 * Maps Supabase snake_case travel_requests row to camelCase TravelRequest domain object.
 */
export const mapDbRequest = (r: any): TravelRequest => ({
  id: r.id,
  submissionId: r.submission_id || r.submissionId || '',
  timestamp: r.created_at || r.timestamp || '',
  requesterId: r.requester_id || r.requesterId || '',
  requesterName: r.requester_name || r.requesterName || '',
  requesterEmail: r.requester_email || r.requesterEmail || '',
  requesterPhone: r.requester_phone || r.requesterPhone || '',
  requesterDepartment: r.requester_department || r.requesterDepartment || '',
  requesterCampus: r.requester_campus || r.requesterCampus || '',
  purpose: r.purpose || '',
  approvingManagerName: r.approving_manager_name || r.approvingManagerName || '',
  approvingManagerEmail: r.approving_manager_email || r.approvingManagerEmail || '',
  tripType: r.trip_type || r.tripType || TripType.ONE_WAY,
  mode: r.travel_mode || r.mode || TravelMode.FLIGHT,
  from: r.from_location || r.from || '',
  to: r.to_location || r.to || '',
  dateOfTravel: r.date_of_travel || r.dateOfTravel || '',
  preferredDepartureWindow: r.preferred_departure_window || r.preferredDepartureWindow || '',
  returnDate: r.return_date || r.returnDate || '',
  returnPreferredDepartureWindow: r.return_preferred_departure_window || r.returnPreferredDepartureWindow || '',
  numberOfTravelers: r.number_of_travelers || r.numberOfTravelers || 1,
  travellerNames: r.traveller_names || r.travellerNames || '',
  priority: r.priority || Priority.MEDIUM,
  specialRequirements: r.special_requirements || r.specialRequirements || '',
  approvalStatus: r.approval_status || r.approvalStatus || ApprovalStatus.PENDING,
  pncStatus: r.pnc_status || r.pncStatus || PNCStatus.NOT_STARTED,
  costCenter: r.cost_center || r.costCenter || '',
  budgetCode: r.budget_code || r.budgetCode || '',
  vendorName: r.vendor_name || r.vendorName || '',
  ticketCost: r.ticket_cost || r.ticketCost || 0,
  travelLegs: r.split_tickets || r.travelLegs || undefined,
  invoiceUrl: r.invoice_url || r.invoiceUrl || '',
  timeline: r.timeline || [],
  emergencyContactName: r.emergency_contact_name || r.emergencyContactName || '',
  emergencyContactPhone: r.emergency_contact_phone || r.emergencyContactPhone || '',
  emergencyContactRelation: r.emergency_contact_relation || r.emergencyContactRelation || '',
  bloodGroup: r.blood_group || r.bloodGroup || '',
  medicalConditions: r.medical_conditions || r.medicalConditions || '',
  hasViolation: r.has_violation || r.hasViolation || false,
  violationDetails: r.violation_reason || r.violationDetails || '',
  bookedBy: r.booked_by || r.bookedBy || '',
  resubmissionCount: r.resubmission_count || r.resubmissionCount || 0,
  onHoldSince: r.on_hold_since || r.onHoldSince,
  cancelledReason: r.cancelled_reason || r.cancelledReason,
  statusChangeReason: r.status_change_reason || r.statusChangeReason,
  infoRequested: r.info_requested || r.infoRequested,
  employeeResponse: r.employee_response || r.employeeResponse,
  advanceId: r.advance_id || r.advanceId,
});
